package com.mseada.tmf.routes;

import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.model.rest.RestBindingMode;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

/**
 * Global REST DSL configuration for the TM Forum Product API implementation.
 *
 * <p>Uses the {@code camel-servlet} component so that the Camel REST DSL is
 * served through Spring Boot's embedded Tomcat on the same port (no separate
 * Netty/Jetty server needed).
 *
 * <h3>OpenAPI documentation endpoints</h3>
 * <ul>
 *   <li>{@code /camel/api-doc}   – live spec auto-generated by {@code camel-openapi-java}
 *       from the REST DSL definitions in {@link ProductCatalogRoute} and
 *       {@link ProductOrderingRoute}.</li>
 *   <li>{@code /api-docs/tmf620} – official TMF620 Product Catalog Management reference
 *       spec (OAS 3.0, v5.0.0), served as-is from
 *       {@code src/main/resources/openapi/tmf620-product-catalog-management.yaml}.</li>
 *   <li>{@code /api-docs/tmf622} – official TMF622 Product Ordering Management reference
 *       spec (Swagger 2.0, v4.0.0), served as-is from
 *       {@code src/main/resources/openapi/tmf622-product-ordering-management.yaml}.</li>
 *   <li>{@code /swagger-ui.html} – Swagger UI (via springdoc-openapi) listing all three
 *       specs in a drop-down selector.</li>
 * </ul>
 *
 * <h3>TMForum path alignment</h3>
 * <ul>
 *   <li>TMF620 routes: {@code /productCatalogManagement/v4/catalog}
 *       (TMF620 v5 official spec uses {@code /productCatalogManagement/v5/productCatalog})</li>
 *   <li>TMF622 routes: {@code /productOrderingManagement/v4/productOrder}
 *       (aligns exactly with TMF622 v4 official spec)</li>
 * </ul>
 */
@Component
public class RestConfigurationRoute extends RouteBuilder {

    @Value("${server.port:8080}")
    private int serverPort;

    @Value("${camel.servlet.mapping.context-path:/camel/*}")
    private String contextPath;

    @Override
    public void configure() {
        restConfiguration()
            .component("servlet")
            .bindingMode(RestBindingMode.json)
            .dataFormatProperty("prettyPrint", "true")
            // Live auto-generated spec endpoint (served by camel-openapi-java)
            .apiContextPath("/api-doc")
            .apiContextRouteId("api-doc-route")
            // API metadata — reflected in the Camel-generated spec
            .apiProperty("api.title", "TM Forum Product APIs — Camel Implementation")
            .apiProperty("api.version", "4.0.0")
            .apiProperty("api.description",
                "Apache Camel + Spring Boot implementation of TM Forum Open APIs: "
                + "TMF620 Product Catalog Management (v4 paths, aligned to official v5 spec) "
                + "and TMF622 Product Ordering Management (v4, aligned to official v4 spec). "
                + "Official TMForum reference specs are served at /api-docs/tmf620 and "
                + "/api-docs/tmf622. Swagger UI is available at /swagger-ui.html.")
            .apiProperty("info.contact.name", "TM Forum")
            .apiProperty("info.contact.url", "https://www.tmforum.org/")
            .apiProperty("cors", "true")
            .port(serverPort)
            .contextPath(contextPath.replace("/*", ""));
    }
}
