package com.mseada.tmf.routes;

import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.model.rest.RestBindingMode;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

/**
 * Global REST DSL configuration.
 *
 * <p>Uses the {@code camel-servlet} component so that the Camel REST DSL is
 * served through Spring Boot's embedded Tomcat on the same port as the rest of
 * the application (no separate Netty/Jetty server needed).
 *
 * <p>OpenAPI documentation is auto-generated by {@code camel-openapi-java} and
 * exposed at {@code /api-doc}.
 */
@Component
public class RestConfigurationRoute extends RouteBuilder {

    @Value("${server.port:8080}")
    private int serverPort;

    @Value("${camel.servlet.mapping.context-path:/camel/*}")
    private String contextPath;

    @Override
    public void configure() {
        restConfiguration()
            .component("servlet")
            .bindingMode(RestBindingMode.json)
            .dataFormatProperty("prettyPrint", "true")
            .apiContextPath("/api-doc")
            .apiContextRouteId("api-doc-route")
            .apiProperty("api.title", "TM Forum Product APIs")
            .apiProperty("api.version", "4.0.0")
            .apiProperty("api.description",
                "Implementation of TMF620 Product Catalog Management and " +
                "TMF622 Product Ordering Management APIs using Apache Camel")
            .apiProperty("cors", "true")
            .port(serverPort)
            .contextPath(contextPath.replace("/*", ""));
    }
}
